-
  About 400 billion gallons water is used worldwide each day.
-
  The moon is one million times drier than the Gobi Desert.
-
  Earth travels through space at 66,700 miles per hour.
-
  From a distance, Earth would be the brightest of the 9 planets. This is because sunlight is reflected by the planet's water.
-
  Asia Continent is covered 30% of the total earth land area, but represent 60% of the world's population.
-
  The Persian Gulf is the warmest sea. In the summer its temperature reaches 35.6 degrees centigrade.
-
  Only 3% water of the earth is fresh, rest 97% salted. Of that 3%, over 2% is frozen in ice sheets and glaciers. Means less than 1% fresh water is found in lakes, rivers and underground.
-
  The total surface area of the Earth is 197 million square miles.
-
  Louisiana loses about 30 square miles (78 square kilometers) of land each year to coastal erosion, hurricanes, other natural and human causes and a thing called subsidence, which means sinking.
-
  Sunlight can penetrate clean ocean water to a depth of 240 feet.